export const collaborators = [
  {
    first_name: 'Davide',
    last_name: 'Dal Pos',
    institution: 'University of Central Florida',
    country: 'USA',
    lat: 28.6026,
    lng: -81.2001,
    leader: 'yes',
    administrator: 'yes',
    orcid: 'https://orcid.org/0000-0002-9122-934X',
    researchgate: 'https://www.researchgate.net/profile/Davide-Dal-Pos-2',
    googlescholar: 'https://scholar.google.com/citations?user=wYj3d_oAAAAJ',
    image: '/images/collaborators/DavideDalPos.jpg'
  },
  {
    first_name: 'Filippo',
    last_name: 'Di Giovanni',
    institution: 'University of Siena',
    country: 'Italy',
    lat: 43.3192,
    lng: 11.3328,
    leader: 'no',
    administrator: 'yes',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Rachel',
    last_name: 'Behm',
    institution: 'University of Central Florida',
    country: 'USA',
    lat: 28.6026,
    lng: -81.2001,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Alexey',
    last_name: 'Reshchikov',
    institution: 'University of Hong Kong',
    country: 'Hong Kong',
    lat: 22.2833,
    lng: 114.1366,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Alvaro',
    last_name: 'Doria dos Santos',
    institution: 'Federal University of Tocantins',
    country: 'Brazil',
    lat: -10.1790,
    lng: -48.3597,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Andrés Fabián',
    last_name: 'Herrera-Flórez',
    institution: 'University of Bonn',
    country: 'Germany',
    lat: 50.7338,
    lng: 7.1023,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Augustijn',
    last_name: 'De Ketelaere',
    institution: 'Indipendent Resaercher',
    country: 'Belgium',
    lat: 51.2194,
    lng: 4.4025,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Fons',
    last_name: 'Verheyde',
    institution: 'Vlaams Instituut Voor De Zee',
    country: 'Belgium',
    lat: 51.22328,
    lng: 2.9397,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Gavin R.',
    last_name: 'Broad',
    institution: 'Natural History Museum, London',
    country: 'UK',
    lat: 51.4969,
    lng: -0.1765,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Helena',
    last_name: 'Onody',
    institution: 'Universidade Estadual do Piauí',
    country: 'Brazil',
    lat: -5.0759,
    lng: -42.8263,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Lennart',
    last_name: 'Bendixen',
    institution: 'Independent Researcher',
    country: 'Germany',
    lat: 52.5200,
    lng: 13.4050,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Rodrigo',
    last_name: 'Araujo',
    institution: 'Universidad Católica del Maule',
    country: 'Chile',
    lat: -35.4262,
    lng: -71.6199,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'Simon',
    last_name: 'van Noort',
    institution: 'Iziko South African Museum, Cape Town',
    country: 'South Africa',
    lat: -33.9286,
    lng: 18.4249,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  },
  {
    first_name: 'William',
    last_name: 'Pénigot',
    institution: 'Independent Researcher',
    country: 'France',
    lat: 48.8566,
    lng: 2.3522,
    leader: 'no',
    administrator: 'no',
    orcid: '',
    researchgate: '',
    googlescholar: '',
    image: ''
  }
]
